auto: true
pygments: true
github: fgnass

author:
  name: Felix Gnass
  email: fgnass@gmail.com
  gravatar: 7014e667cb86fc0cbb9414df5bfafd89
  twitter: fgnass

disqus: fgnass
analytics: 'UA-19036385-2'
